package com.myspace.onelife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class benificiaries implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "benificiaryType")
	private java.lang.String benificiaryType;
	@org.kie.api.definition.type.Label(value = "fullName")
	private java.lang.String fullName;
	@org.kie.api.definition.type.Label(value = "dateOfBirth")
	private java.lang.String dateOfBirth;
	@org.kie.api.definition.type.Label(value = "idNo")
	private java.lang.String idNo;
	@org.kie.api.definition.type.Label(value = "gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label(value = "relationship")
	private java.lang.String relationship;

	public benificiaries() {
	}

	public java.lang.String getBenificiaryType() {
		return this.benificiaryType;
	}

	public void setBenificiaryType(java.lang.String benificiaryType) {
		this.benificiaryType = benificiaryType;
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.lang.String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(java.lang.String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public java.lang.String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(java.lang.String idNo) {
		this.idNo = idNo;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(java.lang.String relationship) {
		this.relationship = relationship;
	}

	public benificiaries(java.lang.String benificiaryType,
			java.lang.String fullName, java.lang.String dateOfBirth,
			java.lang.String idNo, java.lang.String gender,
			java.lang.String relationship) {
		this.benificiaryType = benificiaryType;
		this.fullName = fullName;
		this.dateOfBirth = dateOfBirth;
		this.idNo = idNo;
		this.gender = gender;
		this.relationship = relationship;
	}

}