package com.myspace.onelife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class notification implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "referenceNumber")
	private java.lang.String referenceNumber;
	@org.kie.api.definition.type.Label(value = "notificationType")
	private java.lang.String notificationType;
	@org.kie.api.definition.type.Label(value = "operatorCode")
	private java.lang.String operatorCode;
	@org.kie.api.definition.type.Label(value = "roleId")
	private java.lang.String roleId;

	public notification() {
	}

	public java.lang.String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(java.lang.String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public java.lang.String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(java.lang.String notificationType) {
		this.notificationType = notificationType;
	}

	public java.lang.String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(java.lang.String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public java.lang.String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(java.lang.String roleId) {
		this.roleId = roleId;
	}

	public notification(java.lang.String referenceNumber,
			java.lang.String notificationType, java.lang.String operatorCode,
			java.lang.String roleId) {
		this.referenceNumber = referenceNumber;
		this.notificationType = notificationType;
		this.operatorCode = operatorCode;
		this.roleId = roleId;
	}

}