package com.myspace.onelife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class policyInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "policyClaimAmount")
	private java.lang.String policyClaimAmount;
	@org.kie.api.definition.type.Label(value = "benificiaries")
	private java.util.List<com.myspace.onelife.benificiaries> benificiaries;

	public policyInfo() {
	}

	public java.lang.String getPolicyClaimAmount() {
		return this.policyClaimAmount;
	}

	public void setPolicyClaimAmount(java.lang.String policyClaimAmount) {
		this.policyClaimAmount = policyClaimAmount;
	}

	public java.util.List<com.myspace.onelife.benificiaries> getBenificiaries() {
		return this.benificiaries;
	}

	public void setBenificiaries(
			java.util.List<com.myspace.onelife.benificiaries> benificiaries) {
		this.benificiaries = benificiaries;
	}

	public policyInfo(java.lang.String policyClaimAmount,
			java.util.List<com.myspace.onelife.benificiaries> benificiaries) {
		this.policyClaimAmount = policyClaimAmount;
		this.benificiaries = benificiaries;
	}

}