package com.myspace.onelife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class slaObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("claimType")
	private java.lang.String claimType;
	@org.kie.api.definition.type.Label("persona")
	private java.lang.String persona;

	@org.kie.api.definition.type.Label(value = "slaResult")
	private java.util.List<com.myspace.onelife.slaResult> slaResult;

	public slaObject() {
	}

	public java.lang.String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(java.lang.String claimType) {
		this.claimType = claimType;
	}

	public java.lang.String getPersona() {
		return this.persona;
	}

	public void setPersona(java.lang.String persona) {
		this.persona = persona;
	}

	public java.util.List<com.myspace.onelife.slaResult> getSlaResult() {
		return this.slaResult;
	}

	public void setSlaResult(
			java.util.List<com.myspace.onelife.slaResult> slaResult) {
		this.slaResult = slaResult;
	}

	public slaObject(java.lang.String claimType, java.lang.String persona,
			java.util.List<com.myspace.onelife.slaResult> slaResult) {
		this.claimType = claimType;
		this.persona = persona;
		this.slaResult = slaResult;
	}

}