package com.myspace.onelife;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class taskData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("claims")
	private com.myspace.onelife.claims claims;
	@org.kie.api.definition.type.Label("claimsProcessId")
	private java.lang.Integer claimsProcessId;
	@org.kie.api.definition.type.Label("taskOwner")
	private java.lang.String taskOwner;
	@org.kie.api.definition.type.Label("taskProcessId")
	private java.lang.Integer taskProcessId;
	@org.kie.api.definition.type.Label("taskStatus")
	private java.lang.String taskStatus;
	@org.kie.api.definition.type.Label("taskCreationTime")
	private java.time.LocalDateTime taskCreationTime;
	@org.kie.api.definition.type.Label("taskCreatedBy")
	private java.lang.String taskCreatedBy;

	@org.kie.api.definition.type.Label("claimtype")
	private java.lang.String claimtype;

	@org.kie.api.definition.type.Label("persona")
	private java.lang.String persona;

	@org.kie.api.definition.type.Label("taskId")
	private java.lang.String taskId;

	@org.kie.api.definition.type.Label("taskDescription")
	private java.lang.String taskDescription;

	@org.kie.api.definition.type.Label("taskAssessor")
	private java.lang.String taskAssessor;

	@org.kie.api.definition.type.Label("taskOwnerRole")
	private java.lang.String taskOwnerRole;

	@org.kie.api.definition.type.Label(value = "taskOwnerRM")
	private java.lang.String taskOwnerRM;

	@org.kie.api.definition.type.Label(value = "caseType")
	private java.lang.String caseType;

	public taskData() {
	}

	public com.myspace.onelife.claims getClaims() {
		return this.claims;
	}

	public void setClaims(com.myspace.onelife.claims claims) {
		this.claims = claims;
	}

	public java.lang.Integer getClaimsProcessId() {
		return this.claimsProcessId;
	}

	public void setClaimsProcessId(java.lang.Integer claimsProcessId) {
		this.claimsProcessId = claimsProcessId;
	}

	public java.lang.String getTaskOwner() {
		return this.taskOwner;
	}

	public void setTaskOwner(java.lang.String taskOwner) {
		this.taskOwner = taskOwner;
	}

	public java.lang.Integer getTaskProcessId() {
		return this.taskProcessId;
	}

	public void setTaskProcessId(java.lang.Integer taskProcessId) {
		this.taskProcessId = taskProcessId;
	}

	public java.lang.String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(java.lang.String taskStatus) {
		this.taskStatus = taskStatus;
	}

	public java.time.LocalDateTime getTaskCreationTime() {
		return this.taskCreationTime;
	}

	public void setTaskCreationTime(java.time.LocalDateTime taskCreationTime) {
		this.taskCreationTime = taskCreationTime;
	}

	public java.lang.String getTaskCreatedBy() {
		return this.taskCreatedBy;
	}

	public void setTaskCreatedBy(java.lang.String taskCreatedBy) {
		this.taskCreatedBy = taskCreatedBy;
	}

	public java.lang.String getClaimtype() {
		return this.claimtype;
	}

	public void setClaimtype(java.lang.String claimtype) {
		this.claimtype = claimtype;
	}

	public java.lang.String getPersona() {
		return this.persona;
	}

	public void setPersona(java.lang.String persona) {
		this.persona = persona;
	}

	public java.lang.String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(java.lang.String taskId) {
		this.taskId = taskId;
	}

	public java.lang.String getTaskDescription() {
		return this.taskDescription;
	}

	public void setTaskDescription(java.lang.String taskDescription) {
		this.taskDescription = taskDescription;
	}

	public java.lang.String getTaskAssessor() {
		return this.taskAssessor;
	}

	public void setTaskAssessor(java.lang.String taskAssessor) {
		this.taskAssessor = taskAssessor;
	}

	public java.lang.String getTaskOwnerRole() {
		return this.taskOwnerRole;
	}

	public void setTaskOwnerRole(java.lang.String taskOwnerRole) {
		this.taskOwnerRole = taskOwnerRole;
	}

	public java.lang.String getTaskOwnerRM() {
		return this.taskOwnerRM;
	}

	public void setTaskOwnerRM(java.lang.String taskOwnerRM) {
		this.taskOwnerRM = taskOwnerRM;
	}

	public java.lang.String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(java.lang.String caseType) {
		this.caseType = caseType;
	}

	public taskData(com.myspace.onelife.claims claims,
			java.lang.Integer claimsProcessId, java.lang.String taskOwner,
			java.lang.Integer taskProcessId, java.lang.String taskStatus,
			java.time.LocalDateTime taskCreationTime,
			java.lang.String taskCreatedBy, java.lang.String claimtype,
			java.lang.String persona, java.lang.String taskId,
			java.lang.String taskDescription, java.lang.String taskAssessor,
			java.lang.String taskOwnerRole, java.lang.String taskOwnerRM,
			java.lang.String caseType) {
		this.claims = claims;
		this.claimsProcessId = claimsProcessId;
		this.taskOwner = taskOwner;
		this.taskProcessId = taskProcessId;
		this.taskStatus = taskStatus;
		this.taskCreationTime = taskCreationTime;
		this.taskCreatedBy = taskCreatedBy;
		this.claimtype = claimtype;
		this.persona = persona;
		this.taskId = taskId;
		this.taskDescription = taskDescription;
		this.taskAssessor = taskAssessor;
		this.taskOwnerRole = taskOwnerRole;
		this.taskOwnerRM = taskOwnerRM;
		this.caseType = caseType;
	}

}